# -*- coding: utf-8 -*-
"""rise_spatial_multiplicative_norm_zero_cineca.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-4UndkKCTVbDRQZql3km54NZicEG05gb

### ***Cineca***
"""

import tensorflow as tf
#from tensorflow.keras import layers, activations, callbacks, models
import numpy as np
import pickle
import os
from keras.models import load_model
from skimage.transform import resize
from tqdm import tqdm
import copy
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
import sys
import datetime

"""
##### ***Data & Black-Box***

"""

RESULT_DIR = str(sys.argv[1])
print(f"RESULT_DIR: {RESULT_DIR}")

# IMPORTO I DATI PER VOTTIGNASCO
import os

# Ottieni il percorso effettivo da una variabile d'ambiente
#work_path = os.environ['WORK']  # Ottieni il valore della variabile d'ambiente WORK
#v_test_OHE_path = os.path.join(work_path, "Water_Resources/rise-video/data/Vottignasco/Vottignasco_00425010001_test_month_OHE.npy")
v_test_OHE_path = "/leonardo_work/try25_pellegrino/Water_Resources/rise-video/data/Vottignasco/Vottignasco_00425010001_test_month_OHE.npy"
#v_test_image_path = os.path.join(work_path, "Water_Resources/rise-video/data/Vottignasco/Vottignasco_00425010001_test_normalized_image_sequences.npy")
v_test_image_path = "/leonardo_work/try25_pellegrino/Water_Resources/rise-video/data/Vottignasco/Vottignasco_00425010001_test_normalized_image_sequences.npy"
#v_test_target_dates_path = os.path.join(work_path, "Water_Resources/rise-video/data/Vottignasco/Vottignasco_00425010001_test_target_dates.npy")
v_test_target_dates_path = "/leonardo_work/try25_pellegrino/Water_Resources/rise-video/data/Vottignasco/Vottignasco_00425010001_test_target_dates.npy"
#v_test_normalization_factors_std_path  = os.path.join(work_path, "Water_Resources/rise-video/data/Vottignasco/normalization_factors/Vottignasco_00425010001_training_target_std.npy")
v_test_normalization_factors_std_path = "/leonardo_work/try25_pellegrino/Water_Resources/rise-video/data/Vottignasco/normalization_factors/Vottignasco_00425010001_training_target_std.npy"
#v_test_normalization_factors_mean_path = os.path.join(work_path, "Water_Resources/rise-video/data/Vottignasco/normalization_factors/Vottignasco_00425010001_training_target_mean.npy")
v_test_normalization_factors_mean_path = "/leonardo_work/try25_pellegrino/Water_Resources/rise-video/data/Vottignasco/normalization_factors/Vottignasco_00425010001_training_target_mean.npy"

# Carica l'array numpy dai file
vottignasco_test_OHE    = np.load(v_test_OHE_path)
vottignasco_test_image  = np.load(v_test_image_path)
vottignasco_test_dates  = np.load(v_test_target_dates_path)
vott_target_test_std    = np.load(v_test_normalization_factors_std_path) 
vott_target_test_mean   = np.load(v_test_normalization_factors_mean_path)

print(len(vottignasco_test_dates))
print(len(vottignasco_test_image))
print(len(vottignasco_test_OHE))

#print(vottingasco_test_OHE[0], "\n")
#print(vottignasco_test_image[0][0], "\n")

# """##### ***Black Boxes***""

# Se vuoi abilitare il dropout a runtime
mc_dropout = True

# Definizione della classe personalizzata doprout_custom
class doprout_custom(tf.keras.layers.SpatialDropout1D):
    def call(self, inputs, training=None):
        if mc_dropout:
            return super().call(inputs, training=True)
        else:
            return super().call(inputs, training=False)

# Percorso della directory su Cineca
#base_dir = os.path.join(os.environ['WORK'], "Water_Resources/rise-video/trained_models/seq2val/Vottignasco")
base_dir  = "/leonardo_work/try25_pellegrino/Water_Resources/rise-video/trained_models/seq2val/Vottignasco"
lstm_suffix = 'time_dist_LSTM'

vott_lstm_models = []

def extract_index(filename):
    """Funzione per estrarre l'indice finale dal nome del file."""
    return int(filename.split('_LSTM_')[-1].split('.')[0])

# Trova tutti i file .keras nella cartella e li aggiunge alla lista
for filename in os.listdir(base_dir):
    if lstm_suffix in filename and filename.endswith(".keras"):
        vott_lstm_models.append(os.path.join(base_dir, filename))

# Ordina i modelli in base all'indice finale
vott_lstm_models = sorted(vott_lstm_models, key=lambda x: extract_index(os.path.basename(x)))

# Lista per i modelli caricati
vott_lstm_models_loaded = []

for i, model_lstm_path in enumerate(vott_lstm_models[:10]):  # Prendo i primi 10 modelli ordinati
    #print(f"Caricamento del modello LSTM {i+1}: {model_lstm_path}")

    # Carico il modello con la classe custom
    model = load_model(model_lstm_path, custom_objects={"doprout_custom": doprout_custom})

    # Aggiungo il modello alla lista
    vott_lstm_models_loaded.append(model)

print(vott_lstm_models_loaded)

### ***Temporal-RISE***

#### ***Generation Masks (1D): Uniforme***

import numpy as np
from tqdm import tqdm

def generate_masks_1d(N, input_size, seed=42, **kwargs):
    """
    Parametri:
    - input_size: è il nr di time-step -> scalare
    """
    l = kwargs.get("l", 3)  # La lunghezza della small_mask
    p1 = kwargs.get("p1", 0.5)  # Probabilità di attivazione della maschera

    np.random.seed(seed)

    # Genera una maschera 1D casuale (lunghezza = small_mask_length)
    grid = np.random.rand(N, l) < p1
    grid = grid.astype('float32')  # Trasforma in formato float32

    # Crea una struttura per le maschere finali
    masks = np.empty((N, input_size))  # Maschere finali di dimensione (N, H)

    for i in tqdm(range(N), desc='Generating masks'):
        # Calcola i punti di interpolazione
        x = np.linspace(0, l - 1, l)  # Indici della maschera piccola
        new_x = np.linspace(0, l - 1, input_size)  # Nuovi punti per la dimensione H

        # Interpolazione 1D
        interpolated_mask = np.interp(new_x, x, grid[i])  # Interpola la maschera

        # Applica la maschera interpolata alla maschera finale
        masks[i, :] = interpolated_mask

    # Filtra le maschere che sono tutte 0.0
    #masks = masks[~(masks == 0).all(axis=1)]  # Filtra lungo l'asse della dimensione 1 (H)

    return masks

#### ***Application Masks***

def multiplicative_uniform_noise_onechannel(images, masks, channel, **kwargs):
    std_zero_value = kwargs.get("std_zero_value", -0.6486319166678826)

    masked = []

    # Itero su tutte le N maschere generate
    for mask in masks:
        masked_images = copy.deepcopy(images)  # Copia profonda delle immagini originali

        for t in range(len(mask)):
          masked_images[t][..., channel] = masked_images[t][..., channel] * mask[t] + (1-mask[t]) * std_zero_value

        masked.append(masked_images)

    return masked

#### ***Prediction with Black-Box***
def ensemble_predict(models, images, x3_exp, batch_size=1000):
    # Assicuriamoci che images sia una lista
    if not isinstance(images, list):
        images = [images]

    len_x3 = len(images)

    # Convertiamo x3_exp in un tensore replicato per ogni immagine
    x3_exp_tensor = tf.convert_to_tensor(x3_exp, dtype=tf.float32)

    # Lista per raccogliere le predizioni finali
    final_preds = []

    # Processamento a batch
    for i in range(0, len_x3, batch_size):
        batch_images = images[i:i + batch_size]
        batch_len = len(batch_images)

        # Conversione batch in tensori
        Y_test = tf.stack([tf.convert_to_tensor(img, dtype=tf.float32) for img in batch_images])
        Y_test_x3 = tf.tile(tf.expand_dims(x3_exp_tensor, axis=0), [batch_len, 1, 1])

        # Raccoglie le predizioni di tutti i modelli per il batch corrente
        batch_preds = []

        for model in models:
            preds = model.predict([Y_test, Y_test_x3], verbose=0)
            batch_preds.append(preds)

        # Converte le predizioni del batch in un tensore e calcola la media
        batch_preds_tensor = tf.stack(batch_preds)
        mean_batch_preds = tf.reduce_mean(batch_preds_tensor, axis=0)

        # Aggiunge le predizioni del batch alla lista finale
        final_preds.extend(mean_batch_preds.numpy())

    return np.array(final_preds)

"""#### ***Saliency Map***"""

def calculate_saliency_map_ev_masks(N, weights, masks):
    """
    Calcola la mappa di salienza media data una serie di predizioni e maschere.

    :param weights_array: Array di predizioni (pesi delle maschere).
    :param masks: Array di maschere (numero di maschere x dimensioni maschera).
    :return: Mappa di salienza media.
    """
    sal = []
    
    for j in range(len(masks)):
        sal_j = weights[j] * masks[j]
        sal.append(sal_j)

    # Ora calcola la media lungo l'asse 0
    ev_masks = np.mean(masks, axis=0)

    sal = (1/(ev_masks * N)) * np.sum(sal, axis=0)  # aggiunta della frazione 1/valore_atteso(maschere)

    return np.squeeze(sal)

def calculate_saliency_map_ev_masks_cond_var(N, weights, ref, masks):
    """
    Calcola la mappa di salienza media data una serie di predizioni e maschere.
    VARIANZA CONDIZIONATA

    :param weights_array: Array di predizioni (pesi delle maschere).
    :param masks: Array di maschere (numero di maschere x dimensioni maschera).
    :return: Mappa di salienza media.
    """
    sal = []
    
    for j in range(len(masks)):
        sal_j = ((weights[j] - ref)**2) * masks[j]
        sal.append(sal_j)

    # Ora calcola la media lungo l'asse 0
    ev_masks = np.mean(masks, axis=0)

    sal = (1/(ev_masks * N)) * np.sum(sal, axis=0)  # aggiunta della frazione 1/valore_atteso(maschere)

    return np.squeeze(sal)

def calculate_saliency_map_ev_masks_cond_bias(N, weights, ref, masks):
    """
    Calcola la mappa di salienza media data una serie di predizioni e maschere.
    VARIANZA CONDIZIONATA

    :param weights_array: Array di predizioni (pesi delle maschere).
    :param masks: Array di maschere (numero di maschere x dimensioni maschera).
    :return: Mappa di salienza media.
    """
    sal = []
    
    for j in range(len(masks)):
        sal_j = (weights[j] - ref) * masks[j]
        sal.append(sal_j)

    # Ora calcola la media lungo l'asse 0
    ev_masks = np.mean(masks, axis=0)

    sal = (1/(ev_masks * N)) * np.sum(sal, axis=0)  # aggiunta della frazione 1/valore_atteso(maschere)

    return np.squeeze(sal)

"""#### ***Temporal-RISE: Framework***"""

def rise_temporal_explain(nr_instance, data_test_image, data_test_OHE, models, channel,
                          N, generate_masks_fn, seed, perturb_instance_fn, calculate_saliency_map_fn, H_station=390.0, **kwargs):
  print(f"############################### RISE-Temporal on Instance #{nr_instance} ###########################")
  instance    = copy.deepcopy(data_test_image[nr_instance])
  x3_instance = copy.deepcopy(data_test_OHE[nr_instance])

  input_size = instance.shape[0]
  
  masks = generate_masks_fn(N, input_size, seed, **kwargs)
  perturbed_instances = perturb_instance_fn(instance, masks, channel)

  # Predizione su Istanza Originale
  pred_original = ensemble_predict(models, instance, x3_instance)
  # Predizioni su Istanze Perturbate
  preds_masked = ensemble_predict(models, perturbed_instances, x3_instance)

  # Denormalizzazione Output Black-Box con H_station 
  denorm_pred_original = (pred_original * vott_target_test_std) + vott_target_test_mean
  denorm_preds_masked  = [(pred_masked * vott_target_test_std) + vott_target_test_mean for pred_masked in preds_masked]
  denormalized_H_pred_original = H_station - denorm_pred_original
  denormalized_H_preds_masked  = [H_station - denorm_pred_masked for denorm_pred_masked in denorm_preds_masked]
  # Pesi delle Maschere
  weights = np.concatenate(denormalized_H_preds_masked, axis=0)

  ### S1 
  s1_i = calculate_saliency_map_fn(N, weights, masks)
  ### S2
  s2_i = calculate_saliency_map_ev_masks_cond_var(N, weights, s1_i, masks)
  ### S3 (BIAS)
  s3_i = calculate_saliency_map_ev_masks_cond_bias(N, weights, denormalized_H_pred_original, masks)
  ### S4 (RMSE)
  s4_i = np.sqrt(calculate_saliency_map_ev_masks_cond_var(N, weights, denormalized_H_pred_original, masks))
  print(f"############### Processo completato. Vettore di salienza generata per Istanza #{nr_instance} ###############")
  
  return np.squeeze(s1_i), np.squeeze(s2_i), np.squeeze(s3_i), np.squeeze(s4_i)

#### ***Evaluation Metric***

# Ho implementato anche qui l'approccio a batch per migliorare i tempi di exec

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error

def calculate_auc(x, y):
    """
    Calcola l'area sotto la curva (AUC) utilizzando il metodo del trapezio.

    :param x: Valori dell'asse x (frazione dei pixel inseriti).
    :param y: Valori dell'asse y (errori calcolati).
    :return: Area sotto la curva.
    """
    return np.trapz(y, x)

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error

def update_image_with_important_frame(current_instance, original_instance, t):
    """
    Aggiorna la current_instance inserendo il t-esimo frame.

    :param current_instance: istanza corrente.
    :param original_instance: istanza originale.
    :param t: nr di frame da inserire in current_instance
    :return: istanza aggiornata.
    """
    new_instance = copy.deepcopy(current_instance)
    new_instance[t,:,:,0] = original_instance[t,:,:,0]
    return new_instance


def insertion(models, original_images, x3, important_indices, initial_blurred_images, original_prediction, H_station=390.0):
    """
    Calcola la metrica di inserimento per una spiegazione data.

    :param models: Lista di modelli pre-addestrati.
    :param original_images: Immagine originale.
    :param x3: Codifica one-hot per la previsione.
    :param important_indices: Indici dei pixel in ordine di importanza.
    :param initial_blurred_images: Immagine iniziale con tutti i pixel a zero.
    :return: Lista degli errori ad ogni passo di inserimento.
    """

    # Predizione originale
    #original_prediction = ensemble_predict(models, original_images, x3)[0]
    #print("Original prediction:", original_prediction)

    # Lista per memorizzare le istanze a cui aggiungo frame mano a mano
    insertion_images = [initial_blurred_images]

    # Predizione sull'immagine iniziale (tutti i pixel a zero)
    I_prime = initial_blurred_images.copy()

    # Aggiungere gradualmente i frames più importanti. Ottengo una lista con tutte le img con i frame in maniera graduale
    for t in important_indices:
        #print(frame)
        I_prime = update_image_with_important_frame(I_prime, original_images, t)
        insertion_images.append(I_prime)

    # Calcolo le predizioni sulle istanze a cui ho aggiunto i frame in maniera graduale
    new_predictions = ensemble_predict(models, insertion_images, x3)
    denorm_new_predictions  = [new_prediction * vott_target_test_std + vott_target_test_mean for new_prediction in new_predictions]
    denormalized_H_new_predictions  = [H_station - denorm_new_prediction for denorm_new_prediction in denorm_new_predictions]
    # Rispetto ad ogni suddetta predizione, calcolo il MSE rispetto la pred sull'istanza originaria (come da test-set)
    errors = [mean_squared_error(original_prediction, masked_pred) for masked_pred in denormalized_H_new_predictions[1:]]

    initial_error = mean_squared_error(original_prediction, denormalized_H_new_predictions[0]) # mse immagine con tutti i frame blurrati
    print(f"Initial Prediction with ALL Blurred Frame, pred: {denormalized_H_new_predictions[0]}, error: {initial_error}")
    only_inserted_frame_new_predictions = denormalized_H_new_predictions[1:]
    for t, error in enumerate(errors):
      print(f"Frame {important_indices[t]}, new prediction: {only_inserted_frame_new_predictions[t]}, error: {error}")

    total_errors = [initial_error] + errors
    # Normalizzare la frazione di pixel inseriti
    x = np.linspace(0, 1, len(total_errors))
    print("len total erros: ", len(total_errors))

    # Calcolo dell'AUC
    auc = calculate_auc(x, total_errors)
    print(f"Area under the curve (AUC): {auc}")

    # # Plot della curva dell'errore e area sotto la curva (AUC)
    # plt.plot(x, total_errors, label='Error curve')
    # plt.fill_between(x, total_errors, color='skyblue', alpha=0.4)
    # plt.text(x[-1] * 0.95, max(total_errors) * 0.9, f'AUC: {auc:.2f}',
    #      horizontalalignment='right')  # testo a destra
    # plt.xlabel('Fraction of pixels inserted')
    # plt.ylabel('Mean Squared Error')
    # plt.title('Insertion Metric Curve')
    # plt.legend()
    # plt.show()
    return total_errors,auc

def update_image_by_removing_frame(current_instance, t, std_zero_value=-0.6486319166678826):
    """
    Aggiorna l'immagine inserendo i pixel più importanti.

    :param current_instance: Istanza corrente.
    :param original_instance: Istanza originale.
    :param t: nr frame da rimuovere.
    :return: Istanza aggiornata con il superpixel.
    """
    new_current_instance = current_instance.copy()
    new_current_instance[t,:,:,0] = std_zero_value
    return new_current_instance

def deletion(models, original_images, x3, important_indices, original_prediction, H_station=390.0):
    """
    Calcola la metrica di rimozione per una spiegazione data.

    :param models: Lista di modelli pre-addestrati.
    :param original_images: Immagine originale.
    :param x3: Codifica one-hot per la previsione.
    :param important_indices: Indici dei pixel in ordine di importanza.
    :return: Lista degli errori ad ogni passo di rimozione.
    """

    # Lista per memorizzare le img a cui elimino gradualmente frames
    deletions_images = []

    # Inizializzazione
    I_prime = original_images.copy()

    # Rimuovere gradualmente i frames più importanti
    for t in important_indices:
        I_prime = update_image_by_removing_frame(I_prime, t)
        deletions_images.append(I_prime)

    # Calcolo della predizione su tutte le img a cui rimuovo gradualmente in frames
    new_predictions = ensemble_predict(models, deletions_images, x3)
    denorm_new_predictions  = [new_prediction * vott_target_test_std + vott_target_test_mean for new_prediction in new_predictions]
    denormalized_H_new_predictions  = [H_station - denorm_new_prediction for denorm_new_prediction in denorm_new_predictions]
    # Calcolo del mse rispetto la predizione originale
    errors = [mean_squared_error(original_prediction, masked_pred) for masked_pred in denormalized_H_new_predictions]

    initial_error = 0.0
    print(f"Initial Prediction with Original Images, prediction: {original_prediction}, error: {initial_error}")
    for t, error in enumerate(errors):
      print(f"Removed frame {important_indices[t]}, new prediction: {denormalized_H_new_predictions[t]}, error: {error}")

    total_errors = [initial_error] + errors # Errore iniziale + errori su tutti i pixel rimossi

    # Normalizzare la frazione di pixel rimossi
    x = np.arange(len(total_errors)) / len(total_errors)

    # Calcolo dell'AUC
    auc = calculate_auc(x, total_errors)
    print(f"Area under the curve (AUC): {auc}")

    # # Plot della curva dell'errore e area sotto la curva (AUC)
    # plt.plot(x, total_errors, label='Error curve')
    # plt.fill_between(x, total_errors, color='lightcoral', alpha=0.4)
    # # Posiziona il testo AUC alla destra del titolo
    # plt.text(1.02, 1.02, f'AUC: {auc:.2f}',
    #      horizontalalignment='left',
    #      transform=plt.gca().transAxes,  # Coordinate rispetto all'asse (da 0 a 1)
    #      fontsize=11)
    # plt.xlabel('Fraction of pixels removed')
    # plt.ylabel('Mean Squared Error')
    # plt.title('Deletion Metric Curve')
    # plt.legend()
    # plt.show()
    return total_errors,auc

### Experiments

channel_prec = 0
models = vott_lstm_models_loaded
seed = 42
T,H,W,C = (104,5,8,3)
std_zero_value = -0.6486319166678826
H_station = 390.0

N = 1000

l_values = [16]
p_values = [0.5, 0.6, 0.7, 0.8, 0.9]

len_test_set = len(vottignasco_test_image)

for nr_setup,l in enumerate(l_values):
  print(f"############################## Setup #{nr_setup} ##############################")
  for _, p in enumerate(p_values):
    # Conserva tutte i sal_vecs per tutto il Test-Set
    saliency_vectors = np.zeros((len_test_set,4,T))

    # Errori e AUC Insertion/Deletion tutto il Test-Set
    errors_insertion_all_testset = np.zeros((len_test_set,4, T+1))   # (105, 105)
    auc_insertion_all_testset    = np.zeros((len_test_set,4, 1))     # (105, 1)
    errors_deletion_all_testset  = np.zeros((len_test_set,4, T+1))   # (105, 105)
    auc_deletion_all_testset     = np.zeros((len_test_set,4, 1))     # (105, 1)

    nr_p = str(p).replace('.','') 
    param_combination = f"l_{l}_p_{nr_p}"

    execution_times = []

    print(f"############################## Parameters Combination: {param_combination} ##############################")
    for nr_instance,_ in enumerate(vottignasco_test_image):
       print(f"###################### Explanation for Instance #{nr_instance} ####################################")
       time_start = datetime.datetime.now()

       s1_i,s2_i,s3_i,s4_i = rise_temporal_explain(nr_instance, vottignasco_test_image, vottignasco_test_OHE, models, channel_prec,
                                                N, generate_masks_1d, seed, multiplicative_uniform_noise_onechannel, calculate_saliency_map_ev_masks, H_station, l=l, p1=p)

       time_end = datetime.datetime.now()
       exec_time = (time_end - time_start).total_seconds()
       execution_times.append(exec_time)

       # DEBUG
       print("s1 frame 0:", s1_i[0],"\n")
       print("s2 frame 0:", s2_i[0], "\n")
       print("s3 frame 0:", s3_i[0], "\n")
       print("s4 frame 0:", s4_i[0], "\n")

       saliency_vectors[nr_instance][0] = s1_i
       saliency_vectors[nr_instance][1] = s2_i
       saliency_vectors[nr_instance][2] = s3_i
       saliency_vectors[nr_instance][3] = s4_i

       instance    = copy.deepcopy(vottignasco_test_image[nr_instance])
       x3_instance = copy.deepcopy(vottignasco_test_OHE[nr_instance])

       # Insertion s2,s3,s4
       # Video blurrato da cui partire per l'Insertion. Tutti i pixel di Prec su std_zero_value
       initial_blurred_instance = copy.deepcopy(instance)
       initial_blurred_instance[:,:,:,channel_prec] = std_zero_value

       original_instance = copy.deepcopy(instance)
       original_prediction = ensemble_predict(models, original_instance, x3_instance)
       denormalized_H_original_prediction = H_station - (original_prediction * vott_target_test_std + vott_target_test_mean)
       print(f"Original Prediction: {denormalized_H_original_prediction}")

       all_important_frames_s2 = np.argsort(s2_i)[:] # Importanza max per valori prossimi allo 0
       all_important_frames_s3 = np.argsort(np.abs(s3_i))[:] # Importanza max per valori prossimi allo 0
       all_important_frames_s4 = np.argsort(s4_i)[:] # Importanza max per valori prossimi allo 0
    
       # Insertion
       errors_insertion_s2,auc_insertion_s2 = insertion(models, original_instance, x3_instance, all_important_frames_s2, initial_blurred_instance, denormalized_H_original_prediction) # s2   
       errors_insertion_s3,auc_insertion_s3 = insertion(models, original_instance, x3_instance, all_important_frames_s3, initial_blurred_instance, denormalized_H_original_prediction) # s3
       errors_insertion_s4,auc_insertion_s4 = insertion(models, original_instance, x3_instance, all_important_frames_s4, initial_blurred_instance, denormalized_H_original_prediction) # s4

       for nr_error in range (0, (T+1)):
         errors_insertion_all_testset[nr_instance][1][nr_error] = errors_insertion_s2[nr_error]
         errors_insertion_all_testset[nr_instance][2][nr_error] = errors_insertion_s3[nr_error]
         errors_insertion_all_testset[nr_instance][3][nr_error] = errors_insertion_s4[nr_error]

       auc_insertion_all_testset[nr_instance][1] = auc_insertion_s2
       auc_insertion_all_testset[nr_instance][2] = auc_insertion_s3
       auc_insertion_all_testset[nr_instance][3] = auc_insertion_s4

       #Deletion
       errors_deletion_s2,auc_deletion_s2 = deletion(models, original_instance, x3_instance, all_important_frames_s2, denormalized_H_original_prediction) # s2
       errors_deletion_s3,auc_deletion_s3 = deletion(models, original_instance, x3_instance, all_important_frames_s3, denormalized_H_original_prediction) # s3
       errors_deletion_s4,auc_deletion_s4 = deletion(models, original_instance, x3_instance, all_important_frames_s4, denormalized_H_original_prediction) # s4

       for nr_error in range (0, (T+1)):
         errors_deletion_all_testset[nr_instance][1][nr_error] = errors_deletion_s2[nr_error]
         errors_deletion_all_testset[nr_instance][2][nr_error] = errors_deletion_s3[nr_error]
         errors_deletion_all_testset[nr_instance][3][nr_error] = errors_deletion_s4[nr_error]

       auc_deletion_all_testset[nr_instance][1] = auc_deletion_s2
       auc_deletion_all_testset[nr_instance][2] = auc_deletion_s3
       auc_deletion_all_testset[nr_instance][3] = auc_deletion_s4

    print(f"#################################### END for all Instance in Test-Set for {param_combination} ####################################")
    
    result = {
                "saliency_vectors": saliency_vectors,
                "errors_insertion": errors_insertion_all_testset,
                "auc_insertion": auc_insertion_all_testset,
                "errors_deletion": errors_deletion_all_testset,
                "auc_deletion": auc_deletion_all_testset,
                "parameters_comb": param_combination,
                "execution_times": execution_times  # Lista di nr_instances (105) tempi di exec per ogni istanza
            }
    
    #path_to_save_results = os.path.join(work_path, f"Water_Resources/rise-video/XAI/temporal/results/new_rise_multiplicative_norm_zero/temporal_results_setup_{param_combination}_diff_pred.pkl")
    path_to_save_results = f"{RESULT_DIR}/rise_temporal_original_result_setup_{param_combination}.pkl"
    # Salvataggio della lista results in un file pickle
    with open(path_to_save_results, 'wb') as f:
      pickle.dump(result, f)

print("############################# END FOR ALL SETUPS ##########################################################################")

